
aws:
  credentials:
    - name: AWS Account
      aws_access_key_id: ACCESS_KEY_ID_FROM_AWS
      aws_secret_access_key: SECRET_ACCESS_KEY_ID_FROM_AWS
  notify:
    # use the first credential defined in aws integration by default
    - service: sns
      region_name: us-east-1
      name: sns_us_east_1
      credential_name: AWS Account
      aws_access_key_id: ACCESS_KEY_ID_FROM_AWS
      aws_secret_access_key: SECRET_ACCESS_KEY_ID_FROM_AWS


